# _config.yml
title: "Portfolio of Projects"
description: "A showcase of projects blending technical expertise, creativity, and passion for innovation."
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  projects:
    output: true

# Just the Docs settings
just_the_docs:
  logo: /assets/images/logo.png
  favicon: /assets/images/favicon.ico
  primary_navigation:
    - title: "Home"
      url: /
    - title: "Projects"
      url: /projects/
    - title: "About"
      url: /about/
    - title: "Contact"
      url: /contact/

# Author / social config
author:
  name: Achyuth Kolluru
  email: achyuthkolluru2@gmail.com
  social:
    linkedin: https://www.linkedin.com/in/achyuth-kolluru
    github: https://github.com/AchyuthKolluru
